"""
Project Generator
"""

from pathlib import Path


class ProjectGenerator:

    def create(self, project_name: str):

        root = Path(project_name)

        folders = [
            "src",
            "tests",
            "docs",
        ]

        root.mkdir(exist_ok=True)

        for folder in folders:
            (root / folder).mkdir(exist_ok=True)

        readme = root / "README.md"

        readme.write_text(
            f"# {project_name}\n\nGenerated by TRG.\n",
            encoding="utf-8",
        )

        return root